# -*- coding: utf-8 -*-
"""athletic-gear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fntd0SDGl5wpkY13R5UohQ_z5HthKaAY
"""

import re

senhas = [
  "#forTe1",
  "senhafraca",
  "Qu@s1",
  "Voce@Consegue!2023"
]

senha_forte_regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*(),.?":{}|<>]).{7,}$')

for senha in senhas:
    if senha_forte_regex.match(senha):
        print(senha)